In [1]:
%reload_ext autoreload
%autoreload 2
import tensorflow as tf
import numpy as np
import model
DATAPATH = './data/data.txt'
#return
#X, list of  of ids of words in the document of path
#y, list if next word of X,y[0] is  None


In [2]:
DATAPATH = './data/data.txt'
parameter = model.Parameter(DATAPATH)
data_manager = model.DataManager(parameter)
rnn_model = model.RNN_Model(parameter)


Vocab size 65


TypeError: argmax() got an unexpected keyword argument 'output_type'

In [ ]:
model.train_loop(parameter,rnn_model)

## Define Parameter

In [18]:
DATAPATH = './data/data.txt'
#return
#X, list of  of ids of words in the document of path
#y, list if next word of X,y[0] is  None
parameter = model.Parameter(DATAPATH)

## generate data

In [22]:
data_manager = model.DataManager(parameter)
rnn_model = model.RNN_Model(parameter)
model.train_loop(parameter,rnn_model)

ValueError: Variable W already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "c:\users\steven\anaconda2\envs\gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1226, in __init__
    self._traceback = _extract_stack()
  File "c:\users\steven\anaconda2\envs\gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "c:\users\steven\anaconda2\envs\gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)


In [9]:
data_manager = model.DataManager(parameter)
train_generator,num_batch_train = data_manager.train_batches()
val_generator,num_batch_val = data_manager.val_batches()
tXs,tys = next(train_generator)
vXs,vys= next(val_generator)
print(num_batch_train)
print(tXs)
print('- - - - -- - ')
print(tys)
print('# # # # # #')
print(num_batch_val)
print(vXs)
print('- - - - -- - ')
print(vys)

6099
[array([33, 44, 22, 38]), array([17,  1, 28, 44]), array([17, 44, 39,  4]), array([40, 31, 62, 51]), array([ 4, 64, 49, 22]), array([ 4,  1, 11,  4]), array([ 1, 47, 22, 49]), array([29,  4,  4, 18]), array([ 1,  0, 40,  8]), array([ 1, 64, 19, 22]), array([17,  6,  4, 22]), array([15,  1,  6,  4]), array([ 0, 22,  1,  2]), array([ 4,  1, 38, 47]), array([ 4,  0, 63, 48]), array([62, 62, 30, 50]), array([50, 31, 62, 26]), array([47,  4,  0, 63]), array([15,  1, 38, 47]), array([ 4,  0, 63, 48]), array([62, 62, 33, 44]), array([22, 38, 17,  1]), array([28, 44, 17, 44]), array([39,  4, 40, 31]), array([62, 24, 49, 19]), array([ 1,  0, 22,  4]), array([ 1,  0, 50, 50]), array([ 1, 22,  4, 38]), array([49, 50, 56,  4]), array([18,  1, 22,  0]), array([17,  6,  4, 22]), array([ 1, 17, 49,  1])]
- - - - -- - 
[array([44, 22, 38, 17]), array([ 1, 28, 44, 17]), array([44, 39,  4, 40]), array([31, 62, 51,  4]), array([64, 49, 22,  4]), array([ 1, 11,  4,  1]), array([47, 22, 49, 29]), arra

### Define Model

In [17]:
with tf.Session() as sess:
    #get accuracy
    prob = [[[0.1,0.9],[0.7,0.3],[0.2,0.8],[0.51,0.49]],
            [[0.9,0.1],[0.7,0.3],[0.2,0.8],[0.49,0.51]]
           ]
    correct_answer =[[0,0,1,0],[0,0,1,1]]
    prediction = np.argmax(prob, 2)
    equality = np.equal(prediction, correct_answer)
    accuracy = np.mean(equality)
    print(accuracy)



0.875


In [1]:
import tensorflow as tf

a = tf.constant(1)
b = tf.constant(2)
c = tf.constant(3)

l = [a,b,c]

ab = tf.add(a,b)

with tf.Session() as sess:
    a = tf.constant([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
    index = tf.constant(1)
    s=tf.squeeze(tf.slice(a, tf.stack([0,index]), [ -1,1]),[1])
    
    print(sess.run(s))

[2 5 8]


In [14]:
import numpy as np
a = np.tile([[]],(3,0))
print(a)
print(a.shape)
b = np.array([[],[],[]])
print(b)
print(b.shape)

[]
(3, 0)
[]
(3, 0)


In [16]:
X = tf.placeholder(tf.int32, (None,None))
batch_size = tf.shape(X)[0]
a =  tf.Variable([[]],dtype=tf.float32)
loss_list =  tf.reshape(a,(batch_size,0))
_prob_list =    tf.Variable([],dtype=tf.float32)


cnt = tf.constant(0)
cond  = lambda cnt,loss_list: tf.less(cnt, self.max_seq_len )
print(_prob_list.get_shape())
def loop_body(cnt,loss_list):
    #squeeze 把dimension的大小為1的降維
    time_output = tf.squeeze(tf.slice(self.lstm_h, tf.stack([0,cnt, 0]), [-1,1,-1]),[1])
    #<batch_size,vocab_size>
    logits =  tf.matmul(time_output, self.W_softmax) + self.b_softmax
    #  定義 softxmax ..輸出每一個timestep的機率比較方便預測和採樣
    prob= tf.nn.softmax(logits)
    labels= tf.squeeze(tf.slice(self.y, tf.stack([0,cnt]), [-1,1]),[1])
    loss = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels,logits=logits)
    print("ppp")
    print(loss.get_shape())
  
    return  cnt+1,loss_list
#tensorflow規定每一個當作參數的tensor的shape在while內不能變動,如果要變動必須要用None
# TODO
magic_shape = tf.TensorShape([None,None])
print(_prob_list.get_shape())
tf.while_loop(cond, loop_body, [cnt,loss_list  ],
                      shape_invariants=[cnt.get_shape(),tf.TensorShape([None])])

(0,)
(0,)


ValueError: The shape invariant specified for Reshape_7:0 is not compatible with the initial shape of the loop variable. It enters the loop with shape (?, 0), but the specified shape invariant is (?,).

In [18]:
import numpy as np
print(np.array([[1,2],[3,4],[5,6]]).shape)

(3, 2)


In [21]:
with tf.Session() as sess:
    prob = [[[0.1,0.9],[0.7,0.3],[0.2,0.8],[0.51,0.49]],
            [[0.9,0.1],[0.7,0.3],[0.2,0.8],[0.49,0.51]]
           ]
    prediction = tf.argmax(prob, 2)
    print(sess.run(prediction))

[[1 0 1 0]
 [0 0 1 1]]
